[pytest]
pythonpath = .
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# This tells pytest to NOT run tests in this folder
norecursedirs = tests/agents/example_agentN